### ISSUE TITLE
Setting different title per plot/frame

### ISSUE THREAD

**Issue by AndLen** [jwkvam/celluloid#6]
Is it possible to have a different title set for each frame used in the animation, e.g. for a series of scatterplots?

**Comment by jwkvam** [comment]
Thanks for trying this and asking! There's a related question on [stackoverflow](https://stackoverflow.com/questions/47421486/matplotlib-artist-animation-title-or-text-not-changing). Basically instead of setting the title, you'll have to create a text object, for example:

```
fig, ax = plt.subplots()
for i in range(5):
     ax.text(0.5, 1.01, i, transform=ax.transAxes)
``` 

I'll try to document this in the limitations section.

**Comment by jwkvam** [comment]
Documented in https://github.com/jwkvam/celluloid/commit/18db7a5c0bc40a985aef6925c7ade751ef95a2d7
